/**
 * @typedef GoogleUser
 * @type {Object}
 * @property {string} displayName - the displayed name of the user
 * @property {string} uid - the unique identifier of the google user
 */

/**
 * @typedef Message
 * @type {Object}
 * @property {DocumentId} messageId - document identifier generated by Firestore
 * @property {string} message - the content of the message
 * @property {timestamp} timestamp - epoch timestamp of when the message was sent
 * @property {string} username - the name of the user who sent this message
 */

/**
 * @typedef Room
 * @type {Object}
 * @property {DocumentId} roomId - document identifier generated by Firestore
 * @property {collection} messages - a collection of Message
 * @property {list} participants - a list of ids of the user participants
 */

/**
 * @typedef User
 * @type {Object}
 * @property {string} userId - the uid of the GoogleUser
 * @property {string} displayName - the displayed name of the user
 * @property {string} username - the username of the user
 * @property {list} roomIds - a list of ids of the rooms the user participates in
 * @property {boolean} online - if the user is online
 */

exports.unused = {};