/**
 * @typedef _GoogleUser
 * @type {Object}
 * @property {string} displayName - the displayed name of the user
 * @property {string} uid - the unique identifier of the google user
 */

/**
 * @typedef _Message
 * @type {Object}
 * @property {string} messageId - document identifier generated by Firestore
 * @property {string} message - the content of the message
 * @property {timestamp} timestamp - epoch timestamp of when the message was sent
 * @property {string} username - the username of the [user]{@link _User} who sent this message
 */

/**
 * @typedef _Room
 * @type {Object}
 * @property {string} roomId - document identifier generated by Firestore
 * @property {list} messages - a list of Message
 * @property {list} participants - a list of ids of the [user]{@link _User}
 */

/**
 * @typedef _User
 * @type {Object}
 * @property {string} userId - the uid of the [google user]{@link _GoogleUser}
 * @property {string} displayName - the displayed name of the user
 * @property {string} username - the username of the user
 * @property {list} roomIds - a list of ids of the rooms the user participates in
 * @property {boolean} online - if the user is online
 */
