/**
 * @typedef _GoogleUser
 * @type {Object}
 * @property {string} displayName - the displayed name of the Google user
 * @property {string} uid - the unique identifier of the Google user
 */

/**
 * @typedef _Message
 * @type {Object}
 * @property {string} messageId - document identifier generated by Firestore
 * @property {string} message - the content of the message
 * @property {timestamp} timestamp - epoch timestamp of when the message was sent
 * @property {string} username - the username of the [user]{@link _User} who sent this message
 */

/**
 * @typedef _Room
 * @type {Object}
 * @property {string} roomId - document identifier generated by Firestore
 * @property {list} messages - a list of [messages]{@link _Message} exchanged in this room
 * @property {list} participants - a list of usernames of [users]{@link _User} in this room
 */

/**
 * @typedef _User
 * @type {Object}
 * @property {string} userId - the uid of the [Google user]{@link _GoogleUser}
 * @property {string} displayName - the displayed name of the user
 * @property {boolean} online - if the user is online
 * @property {list} roomIds - the list of [rooms]{@link _Room} the user belongs to
 * @property {string} username - the username of the user
 */
