name: Deploy Dev Branch to Beta
"on":
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm test && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWOTENCHATAPP }}"
          channelId: live
          projectId: twotenchatapp-beta-a41e8
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
