name: Deploy Main Branch to Prod
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build && npm test
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWOTENCHATAPP }}"
          channelId: live
          projectId: twotenchatapp
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
