name: Deploy Dev Branch to Beta Preview
"on": 
  pull_request:
    branches:
      - dev
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    # env:
    #   FIREBASE_CONFIG: "${{ secrets.FIREBASE_CONFIG_BETA }}"
    steps:
      - uses: actions/checkout@v2
      - run: REACT_APP_FIREBASE_CONFIG="${{ secrets.FIREBASE_CONFIG_BETA }}" npm install && npm ci && npm test && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWOTENCHATAPP_BETA }}"
          projectId: twotenchatapp-beta-a41e8
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
          REACT_APP_FIREBASE_CONFIG: "${{ secrets.FIREBASE_CONFIG_BETA }}"
      # - name: Deploy Environment Variables
      #   run: |
      #     export REACT_APP_FIREBASE_CONFIG="${{ env.FIREBASE_CONFIG }}"
      #     echo $REACT_APP_FIREBASE_CONFIG

