name: Deploy Main Branch to Prod Preview
"on": 
  pull_request:
    branches:
      - main
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make main envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_APIKEY: "${{ secrets.FIREBASE_APIKEY }}"
          envkey_REACT_APP_AUTHDOMAIN: "${{ secrets.FIREBASE_AUTHDOMAIN }}"
          envkey_REACT_APP_DATABASEURL: "${{ secrets.FIREBASE_DATABASEURL }}"
          envkey_REACT_APP_PROJECTID: "${{ secrets.FIREBASE_PROJECTID }}"
          envkey_REACT_APP_STORAGEBUCKET: "${{ secrets.FIREBASE_STORAGEBUCKET }}"
          envkey_REACT_APP_MESSAGINGSENDERID: "${{ secrets.FIREBASE_MESSAGINGSENDERID }}"
          envkey_REACT_APP_APPID: "${{ secrets.FIREBASE_APPID }}"
          file_name: .env.main
      - run: npm install && npm ci && npm test && npm run build:main
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWOTENCHATAPP }}"
          projectId: twotenchatapp
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
