name: Deploy Dev Branch to Beta Preview
"on": 
  pull_request:
    branches:
      - dev
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make dev envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_APIKEY: "AIzaSyClt_cw75ffjm45ehfsrcnpCSRm17p0Xyg"
          envkey_REACT_APP_AUTHDOMAIN: "twotenchatapp-beta-a41e8.firebaseapp.com"
          envkey_REACT_APP_DATABASEURL: "https://twotenchatapp-beta-a41e8.firebaseio.com"
          envkey_REACT_APP_PROJECTID: "twotenchatapp-beta-a41e8"
          envkey_REACT_APP_STORAGEBUCKET: "twotenchatapp-beta-a41e8.appspot.com"
          envkey_REACT_APP_MESSAGINGSENDERID: "1056001987312"
          envkey_REACT_APP_APPID: "1:1056001987312:web:c0e59a9e51560b70126835"
          file_name: .env.dev
      - run: npm install && npm ci && npm test && npm run build:dev
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWOTENCHATAPP_BETA }}"
          projectId: twotenchatapp-beta-a41e8
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
