name: Dev Branch Deployment Preview
"on": 
  pull_request:
    branches:
      - dev
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm test && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "firebase-adminsdk-a3qd8@twotenchatapp.iam.gserviceaccount.com"
          projectId: twotenchatapp-beta-a41e8
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
