name: Cypress E2E tests
on: [push]
jobs:
  cypress_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make dev envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_APIKEY: "${{ secrets.FIREBASE_APIKEY_BETA }}"
          envkey_REACT_APP_AUTHDOMAIN: "${{ secrets.FIREBASE_AUTHDOMAIN_BETA }}"
          envkey_REACT_APP_DATABASEURL: "${{ secrets.FIREBASE_DATABASEURL_BETA }}"
          envkey_REACT_APP_PROJECTID: "${{ secrets.FIREBASE_PROJECTID_BETA }}"
          envkey_REACT_APP_STORAGEBUCKET: "${{ secrets.FIREBASE_STORAGEBUCKET_BETA }}"
          envkey_REACT_APP_MESSAGINGSENDERID: "${{ secrets.FIREBASE_MESSAGINGSENDERID_BETA }}"
          envkey_REACT_APP_APPID: "${{ secrets.FIREBASE_APPID_BETA }}"
          envkey_CYPRESS_TEST_UID: "${{ secrets.FIREBASE_TEST_UID_BETA }}"
          file_name: .env.dev
      - name: Install and start local server
        run: npm ci && BROWSER=none npm start
      - name: Run cypress
        run: npm run cy:run:dev

