name: Jest Test Generation and Deployment
"on":
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  run-jest-coverage:
    name: Run Jest coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make dev envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_APIKEY: "${{ secrets.FIREBASE_APIKEY_BETA }}"
          envkey_REACT_APP_AUTHDOMAIN: "${{ secrets.FIREBASE_AUTHDOMAIN_BETA }}"
          envkey_REACT_APP_DATABASEURL: "${{ secrets.FIREBASE_DATABASEURL_BETA }}"
          envkey_REACT_APP_PROJECTID: "${{ secrets.FIREBASE_PROJECTID_BETA }}"
          envkey_REACT_APP_STORAGEBUCKET: "${{ secrets.FIREBASE_STORAGEBUCKET_BETA }}"
          envkey_REACT_APP_MESSAGINGSENDERID: "${{ secrets.FIREBASE_MESSAGINGSENDERID_BETA }}"
          envkey_REACT_APP_APPID: "${{ secrets.FIREBASE_APPID_BETA }}"
          file_name: .env.dev
      - name: Install and test
        run: yarn install --frozen-lockfile && yarn test --coverage
      - name: Deploy coverage html
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_COVERAGE }}
          external_repository: UCSD-MASHED/TaterTalkCoverage
          publish_branch: main
          publish_dir: ./coverage
