name: JSDoc Generation and Deployment
on: [push, pull_request]
jobs:
  run-jsdoc:
    name: Run JSDoc
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install --save-dev jsdoc better-docs

      - name: Build
        run: node jsdoc -c jsdoc.json -d ./out

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: UCSD-MASHED/TaterTalkDoc
          publish_branch: main
          publish_dir: ./out
