name: JSDoc Generation and Deployment
"on":
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  run-jsdoc:
    name: Run JSDoc
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn add better-docs --dev

      - name: Build
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./src
          output_dir: ./out
          config_file: jsdoc.json
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: UCSD-MASHED/TaterTalkDoc
          publish_branch: main
          publish_dir: ./out
